### ISSUE TITLE
roi_align bug in fpn.py

### ISSUE THREAD

**Issue by hongdayu** [guoruoqian/cascade-rcnn_Pytorch#14]
my pytorch is 4.0.
![image](https://user-images.githubusercontent.com/32477868/45662671-5b0c6580-bb35-11e8-91dc-19add9045315.png)
the idx_l sometimes is empty ,raise the out of range error?

**Comment by hongdayu** [comment]
the roi_level is tensor([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
         4.,  4.,  4.,  4.,  4.,  4.,  2.,  3.,  2.,  3.,  2.,  3.,
         3.,  2.,  3.,  3.,  3.,  2.,  2.,  3.,  4.,  3.,  3.,  3.,
         2.,  3.,  3.,  2.,  2.,  3.,  3.,  4.,  2.,  2.,  2.,  2.,
         2.,  2.,  2.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  3.,  3.,
         2.,  3.,  2.,  2.,  3.,  4.,  3.,  2.,  3.,  3.,  2.,  3.,
         4.,  4.,  2.,  4.,  2.,  3.,  2.,  3.,  4.,  3.,  2.,  3.,
         3.,  3.,  2.,  3.,  3.,  3.,  3.,  2.,  3.,  4.,  2.,  3.,
         2.,  4.,  2.,  3.,  3.,  4.,  3.,  2.,  3.,  3.,  2.,  2.,
         2.,  2.,  3.,  4.,  3.,  2.,  2.,  2.,  3.,  3.,  3.,  2.,
         2.,  4.,  4.,  3.,  3.,  2.,  3.,  2.,  3.,  4.,  3.,  3.,
         4.,  3.,  4.,  4.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  3.,
         3.,  4.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,
         3.,  4.,  4.,  3.,  3.,  3.,  3.,  3.,  2.,  2.,  3.,  2.,
         3.,  3.,  3.,  3.,  2.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,
         2.,  4.,  3.,  2.,  4.,  4.,  3.,  2.,  2.,  3.,  4.,  3.,
         3.,  2.,  4.,  2.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,
         2.,  4.,  3.,  3.,  3.,  4.,  3.,  4.,  3.,  2.,  2.,  4.,
         3.,  3.,  3.,  3.,  3.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,
         3.,  3.,  3.,  3.,  2.,  2.,  2.,  5.,  3.,  3.,  2.,  3.,
         4.,  3.,  3.,  2.,  3.,  2.,  3.,  4.,  3.,  3.,  2.,  3.,
         3.,  2.,  3.,  4.], device='cuda:0')
but if condition is not True,so raise the error,

**Comment by hongdayu** [comment]
sorrr,  the size of idx_l sometimes is empty ,
![image](https://user-images.githubusercontent.com/32477868/45663379-af651480-bb38-11e8-8b89-3590fe15c7eb.png)
if idx_l has one element,after squeeze ,the idx_l is not a vetor

**Comment by hongdayu** [comment]
it is work for me:
idx_l = (roi_level == l).nonzero().view(-1)

**Comment by ruoqianguo** [comment]
The 0.4.0 version has a different tensor processing for the 0 dimension than the 0.3.1 version.
