### ISSUE TITLE
RSNA数据集

### ISSUE THREAD

**Issue by hongdayu** [guoruoqian/cascade-rcnn_Pytorch#15]
我用RSNA的数据集进行按照默认参数训练，阈值是 [0.4  0.45 0.5  0.55 0.6  0.65 0.7  0.75]。
结果detnet的效果要好多detnet-cascade
detnet在6epoch，验证集map达到最好：
mAPs:  [0.7224553391260808, 0.6599297035067196, 0.579511199465727, 0.48372004238688515, 0.377126303947345, 0.27479695269073545, 0.19356904730168234, 0.13584048094266832]
mean mAP:  0.4283686336709805
detnet-cascade在5epoch，验证集map达到最好：
mAPs:  [0.6793144470700885, 0.5995099883468915, 0.5322867614959018, 0.44291050802950327, 0.3290775815062264, 0.257612591509458, 0.1926359629090184, 0.14070865806833324]
mean mAP:  0.39675706236692765

@guoruoqian 这是什么原因呢？

**Comment by gittigxuy** [comment]
@hongdayu ,请问如何训练自己的数据集？你将RSNA数据集转化为coco格式还是voc格式了呢？

**Comment by hongdayu** [comment]
> @hongdayu ,请问如何训练自己的数据集？你将RSNA数据集转化为coco格式还是voc格式了呢？

voc啊
