### ISSUE TITLE
what will happen when I training cascade net without cag option?

### ISSUE THREAD

**Issue by weitaoatvison** [guoruoqian/cascade-rcnn_Pytorch#2]
HI, I have trained a model with cascade rcnn. But I did not set the cag option when I trained It, the training stage is successfully, however,  when I do Inference the code crashed.  I noticed that your training script has set the cag option when training. So, how does the option effect? If I want to train a model without cascade, how to set?

**Comment by bruceyang2012** [comment]
@weitaoatvison Do you success to train cascade net without cag option? I have the same problem with you.

**Comment by bruceyang2012** [comment]
@guoruoqian If I train fpn on VOC2007 without cascade and without cag option, I get 76.1 mAP.  However, cascade rcnn with fpn and with cag option on VOC2007 only get 73.4 mAP. So, I want to know the result of cascade rcnn without cag option. Hope you can help me solve the problem.
