### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by lichuang0529** [guoruoqian/cascade-rcnn_Pytorch#24]
I tried to run the trainval_net.py file to train model with VOC 2007 data,But I got an error as following:
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "trainval_net.py", line 375, in <module>
    loss.backward()
  File "/media/t1/0a33a0a0-b876-45c1-bb1c-f0d6fecc3bf9/cascade/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/media/t1/0a33a0a0-b876-45c1-bb1c-f0d6fecc3bf9/cascade/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
Exception socket.error: error(111, 'Connection refused') in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f5351873810>> ignored
DId  anyone get the same error and tell me how to fix it?Thanks a lot!

**Comment by gooodooo** [comment]
Hi，I met the same mistake on 1 1080Ti.
Have solved this problem? 
Thanks

**Comment by ruoqianguo** [comment]
Your GPU memory is full.

**Comment by JungUkKim** [comment]
@lichuang0529, @gooodooo, @guoruoqian 
Maybe this is because of the image resize problem

erase "#" and activate line 47,48  in  /lib/model/utils/blob.py 

If there is no consideration for max scale, a size such as [600, 4000] occurs. Therefore, memory error occurs.
