### ISSUE TITLE
numpy edition problem 

### ISSUE THREAD

**Issue by yuyijie1995** [guoruoqian/cascade-rcnn_Pytorch#3]
![2018-08-26 19-41-27](https://user-images.githubusercontent.com/30818917/44627865-0c214500-a968-11e8-819d-db68532c413d.png)
As you can see ,I already install the numpy but the import error happened .I don't why, my torch version is 0.3.1 ,can you give me some suggestions? like your numpy version .
Thanks a lot

**Comment by yuyijie1995** [comment]
And I have another question is about the dataset ,I have made my dataset like VOC style .VOC2007/*,where should I place it ? is the data file?

**Comment by guoruoqian** [comment]
i trained the model both in numpy version '1.14.3' and '1.15.0'

**Comment by yuyijie1995** [comment]
Thanks a lot  I already solved it.
