### ISSUE TITLE
return nll_loss Error

### ISSUE THREAD

**Issue by yuyijie1995** [guoruoqian/cascade-rcnn_Pytorch#4]
![2018-08-27 09-14-41](https://user-images.githubusercontent.com/30818917/44635668-c9985080-a9d9-11e8-9534-aa3e35864965.png)
I just make my dataset as VOC style ,but this error happened and I do not know
how to slove it  can u give me some suggestions? Thanks

**Comment by lyatdawn** [comment]
Can you save this problem????
