### ISSUE TITLE
How to use multi-GPUs?

### ISSUE THREAD

**Issue by Allenwutao** [guoruoqian/cascade-rcnn_Pytorch#5]
I find the codes can not use multi-GPUs?  Could you help me?

**Comment by guoruoqian** [comment]
you can use multi-GPUs like this `CUDA_VISIBLE_DEVICES=3,4 python3 trainval_net.py exp_name --dataset pascal_voc --net detnet59 --bs 2 --nw 4 --lr 1e-3 --epochs 12 --save_dir weights --cuda --use_tfboard True --cag --cascade --mGPUs`

**Comment by Allenwutao** [comment]
I change the "--nw 4" to "--nw 1". It works. I do not know the reason.

**Comment by guoruoqian** [comment]
i am not sure what happend? can you show your error information when you set '--nw 4'
